import os
# if using Apple MPS, fall back to CPU for unsupported ops
os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"
import numpy as np
import torch
from PIL import Image
from transformers import AutoProcessor, Kosmos2ForConditionalGeneration
from data_utils import *
from tqdm import tqdm
import cv2
import json
import argparse

from pdb import set_trace as stx
import random
import imageio


import cv2
import matplotlib.pyplot as plt
import torchvision
import matplotlib.colors as mcolors
import torchvision.utils
from torchvision.utils import flow_to_image


def sigma_matrix2(sig_x, sig_y, theta):
    """Calculate the rotated sigma matrix (two dimensional matrix).
    Args:
        sig_x (float):
        sig_y (float):
        theta (float): Radian measurement.
    Returns:
        ndarray: Rotated sigma matrix.
    """
    d_matrix = np.array([[sig_x**2, 0], [0, sig_y**2]])
    u_matrix = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
    return np.dot(u_matrix, np.dot(d_matrix, u_matrix.T))


def mesh_grid(kernel_size):
    """Generate the mesh grid, centering at zero.
    Args:
        kernel_size (int):
    Returns:
        xy (ndarray): with the shape (kernel_size, kernel_size, 2)
        xx (ndarray): with the shape (kernel_size, kernel_size)
        yy (ndarray): with the shape (kernel_size, kernel_size)
    """
    ax = np.arange(-kernel_size // 2 + 1., kernel_size // 2 + 1.)
    xx, yy = np.meshgrid(ax, ax)
    xy = np.hstack((xx.reshape((kernel_size * kernel_size, 1)), yy.reshape(kernel_size * kernel_size,
                                                                           1))).reshape(kernel_size, kernel_size, 2)
    return xy, xx, yy


def pdf2(sigma_matrix, grid):
    """Calculate PDF of the bivariate Gaussian distribution.
    Args:
        sigma_matrix (ndarray): with the shape (2, 2)
        grid (ndarray): generated by :func:`mesh_grid`,
            with the shape (K, K, 2), K is the kernel size.
    Returns:
        kernel (ndarrray): un-normalized kernel.
    """
    inverse_sigma = np.linalg.inv(sigma_matrix)
    kernel = np.exp(-0.5 * np.sum(np.dot(grid, inverse_sigma) * grid, 2))
    return kernel

def bivariate_Gaussian(kernel_size, sig_x, sig_y, theta, grid=None, isotropic=True):
    """Generate a bivariate isotropic or anisotropic Gaussian kernel.
    In the isotropic mode, only `sig_x` is used. `sig_y` and `theta` is ignored.
    Args:
        kernel_size (int):
        sig_x (float):
        sig_y (float):
        theta (float): Radian measurement.
        grid (ndarray, optional): generated by :func:`mesh_grid`,
            with the shape (K, K, 2), K is the kernel size. Default: None
        isotropic (bool):
    Returns:
        kernel (ndarray): normalized kernel.
    """
    if grid is None:
        grid, _, _ = mesh_grid(kernel_size)
    if isotropic:
        sigma_matrix = np.array([[sig_x**2, 0], [0, sig_x**2]])
    else:
        sigma_matrix = sigma_matrix2(sig_x, sig_y, theta)
    kernel = pdf2(sigma_matrix, grid)
    kernel = kernel / np.sum(kernel)
    return kernel

def flow_to_color(flow, max_flow=1.0):
    """
    将光流 (H, W, 2) 转换为颜色编码图。
    
    参数:
    - flow: numpy.ndarray, 光流张量，形状为 (H, W, 2)，值范围为 [-1, 1]
    - max_flow: float, 光流的最大值，用于归一化 (默认假设范围是 [-1, 1])

    返回:
    - color_flow: numpy.ndarray, 颜色编码光流图，形状为 (H, W, 3)，值范围为 [0, 255]
    """
    # 计算光流的大小和方向
    u = flow[..., 0]
    v = flow[..., 1]
    magnitude = np.sqrt(u**2 + v**2)  # 大小
    angle = np.arctan2(v, u)  # 方向 (-π, π)

    # 将角度映射到 [0, 1]，用于色调 (hue)
    hue = (angle + np.pi) / (2 * np.pi)

    # 将大小归一化到 [0, 1]
    magnitude = magnitude - np.min(magnitude) / (np.max(magnitude) - np.min(magnitude))


    # HSV 表示 (H: 色调, S: 饱和度, V: 亮度)
    hsv = np.zeros((flow.shape[0], flow.shape[1], 3), dtype=np.float32)
    hsv[..., 0] = hue  # 色调
    hsv[..., 1] = 1.0  # 饱和度 (固定为 1)
    hsv[..., 2] = magnitude  # 亮度

    # 将 HSV 转换为 RGB
    rgb = mcolors.hsv_to_rgb(hsv)  # 使用 matplotlib 的 HSV 转 RGB
    rgb = (rgb * 255).astype(np.uint8)

    background_mask = magnitude == 0
    rgb[background_mask] = [255, 255, 255]  # 设置为白色
    return rgb

def save_optical_flow_video(flow_tensor, file_name, fps=24):
    """
    保存光流张量为 MP4 视频。
    
    参数:
    - flow_tensor: torch.Tensor, 光流张量，形状为 (T, H, W, 2)，值范围为 [-1, 1]
    - file_name: str, 保存的视频文件名，例如 'flow_output.mp4'
    - fps: int, 视频帧率 (默认为 30)
    """
    # 将光流张量转换为 NumPy 数组
    flow_tensor = flow_tensor.cpu().numpy()

    # 创建一个列表，用于存储每一帧的颜色编码光流图
    frames = []
    for t in range(flow_tensor.shape[0]):
        flow_frame = flow_tensor[t]  # 取出单帧光流 (H, W, 2)
        color_frame = flow_to_color(flow_frame)  # 转换为颜色编码图
        frames.append(torch.from_numpy(color_frame))  # 转换为张量
    print(f'>>>> frames[0].shape: {frames[0].shape}')
    # 堆叠所有帧并保存为视频
    video_tensor = torch.stack(frames)
    print(f'>>>> video_tensor.shape: {video_tensor.shape}')
    torchvision.io.write_video(file_name, video_tensor, fps=24, video_codec="h264", options={'crf': '10'})


blur_kernel = bivariate_Gaussian(99, 10, 10, 0, grid=None, isotropic=True)

def get_cropped_flows(
    trajs: torch.Tensor,
    keep_min_prob: float = 0.0,
    keep_max_prob: float = 1.0,
    n_frames: int = 128,
    out_w: int = 640,
    out_h: int = 384,
) -> torch.Tensor:

    ## trajs: b n t 2, has been normalized to [0,1]
    ## trajs.shape = (1, 128, 100, 2)
    # trajs[...,0] = trajs[...,0] * out_w
    # trajs[...,1] = trajs[...,1] * out_h

    # 此处不需要归一化，已经是坐标了


    ## convert to flow
    optical_flow = np.zeros((n_frames, out_h, out_w, 2), dtype=np.float32)

    ## randomly drop some trajectories
    ## 随机保留部分轨迹
    keep_prob = random.uniform(keep_min_prob, keep_max_prob)
    keep_mask = torch.rand(trajs.shape[1]) < keep_prob
    
    # 先把 optical_flow
    for traj_idx in range(trajs.shape[2]):
        if keep_mask[traj_idx]:
            for frame_idx in range(n_frames-1):
                # stx()
                p = trajs[0, frame_idx, traj_idx]
                p1 = trajs[0, frame_idx+1, traj_idx]
                # FIXME: 那这里被 continue 的部分不就乱了吗？
                if p[0] < 0 or p[0] >= out_w or p[1] < 0 or p[1] >= out_h:
                    continue
                optical_flow[frame_idx+1, int(p[1]), int(p[0]), 0] = (p1[0] - p[0])/out_w
                optical_flow[frame_idx+1, int(p[1]), int(p[0]), 1] = (p1[1] - p[1])/out_h
    stx()

    ## debug
    optical_flow_vis = torch.from_numpy(optical_flow).permute(0, 3, 1, 2) # [128, 384, 640, 2] -> [128, 2, 384, 640]
    optical_flow_vis[:,0] = optical_flow_vis[:,0] * out_w
    optical_flow_vis[:,1] = optical_flow_vis[:,1] * out_h
    video_tensor = flow_to_image(optical_flow_vis)      # [128, 3, 384, 640], value range - [-13.25, 18.25]
    video_tensor = video_tensor.permute(0, 2, 3, 1)     # [128, 384, 640, 3], value range - [0, 255]
    file_name = 'track_points.mp4'
    with imageio.get_writer(file_name, mode='I', fps=24) as video:
        for frame in video_tensor:
            video.append_data(frame.numpy())

    stx()
    
    for i in range(1, n_frames):
        optical_flow[i] = cv2.filter2D(optical_flow[i], -1, blur_kernel)
    
    optical_flow = torch.from_numpy(optical_flow) ## [M,h,w,2]

    optical_flow_vis = optical_flow.permute(0, 3, 1, 2)
    optical_flow_vis[:,0] = optical_flow_vis[:,0] * out_w
    optical_flow_vis[:,1] = optical_flow_vis[:,1] * out_h
    video_tensor = flow_to_image(optical_flow_vis) # [T,3,h,w]
    video_tensor = video_tensor.permute(1, 0, 2, 3).float() # [T,h,w,3]
    video_tensor = video_tensor/255.0 *2 -1

    return video_tensor



# 先从 s3 上读取 pred_tracks.npy 以及它对应的 video

s3_bucket_name = 'cis-intern-2024'
s3_track_name = 'yuanhao_cai/VideoEdit/label/video_motion_control/part_0/0_0_10_track.npy'
s3_video_name = 'yuanhao_cai/VideoEdit/raw_data/part_0/0_0_10.mp4'


# track shape: [128, 100, 2]
# video 一个 list, 每个元素是一个 numpy 数组，形状为 (384, 640, 3)
track = read_npy_from_s3(s3_bucket_name, s3_track_name)
video = read_video_from_s3(s3_bucket_name, s3_video_name)



n_frames = len(video)
h, w = video[0].shape[:2]
# stx()

flow_map = get_cropped_flows(track[None], keep_min_prob=0.0, keep_max_prob=1.0, n_frames=n_frames, out_w=w, out_h=h)

stx()